name: Build Docker and deploy to dockerhub

on:
  push:
    branches: [ "master" ]
env:
  DOCKER_REPO : ${{ secrets.MY_DOCKERHUB_REPO }}                                    
  CONTAINER_NAME : node-hello    

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        IMAGE_TAG: latest
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t ${{ env.DOCKER_REPO }}:$IMAGE_TAG .
        docker push ${{ env.DOCKER_REPO }}:$IMAGE_TAG
        echo "image=${{ env.DOCKER_REPO }}:$IMAGE_TAG" >> $GITHUB_OUTPUT
  debug:
    needs: [deploy]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - uses: actions/checkout@v3
      - run: ./debug
